---
- name: Install Java and net-tools
  hosts: aws_ec2
  tasks:
    - name: Update apt repo and cache
      apt: update_cache=yes force_apt_get=yes cache_valid_time=3600
    - name: Installing Java version 8
      apt: name=openjdk-8-jre-headless
    - name: Install net-tools
      apt: name=net-tools

- name: Download and unpack nexus
  hosts: aws_ec2
  tasks: 
    - name: Check if nexus folder already exists
      stat:
        path: /opt/nexus
      register: stat_result
    - name: Download nexus
      get_url:
        url: https://download.sonatype.com/nexus/3/latest-unix.tar.gz
        dest: /opt/
      register: result_download
    - debug: msg={{result_download.dest}}
    - name: Untar nexus installer
      unarchive:
        src: "{{result_download.dest}}"
        dest: /opt/
        remote_src: yes
      when: not stat_result.stat.exists
    - name: Find nexus folder
      find: 
        paths: /opt
        pattern: "nexus-*"
        file_type: directory
      register: result_find
    - debug: msg={{result_find.files[0].path}}
    - debug: msg={{stat_result.stat.exists}}
    - name: Rename nexus folder
      shell: mv {{result_find.files[0].path}} /opt/nexus
      when: not stat_result.stat.exists

- name: Create nexus user to own nexus folders
  hosts: aws_ec2
  tasks:
    - name: Create nexus group
      group: 
        name: nexus
        state: present
    - name: Create nexus user
      user: 
        name: nexus
        group: nexus
    - name: Make nexus user owner of nexus folder
      file:
        path: /opt/nexus
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
    - name: Make nexus user owner of sonatype-work folder
      file:
        path: /opt/sonatype-work
        state: directory
        owner: nexus
        group: nexus
        recurse: yes
- name: Start nexus with nexus user
  hosts: aws_ec2
  become: True
  become_user: nexus
  tasks:
    - name: Set run_as_user nexus
      lineinfile:
        path: /opt/nexus/bin/nexus.rc
        regexp: '^#run_as_user=""'
        line: run_as_user="nexus"
    - name: Starting nexus
      command: /opt/nexus/bin/nexus start

- name: Verify that nexus is running
  hosts: aws_ec2
  tasks:
    - name: Check status with ps
      shell: ps aux | netstat nexus
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
    - name: Waiting one minute
      pause:
        minutes: 1
    - name: Check status with netstat
      shell: netstat -plnt
      register: app_status
    - debug: msg={{app_status.stdout_lines}}
